### PR TITLE
[CI] Build Python wheels for MacOS (x86_64 and arm64)

### LINKED ISSUE #7039: Segmentation fault on MacOS with libomp 12.0.0
The following code results in a Python segmentation fault when executed with Python 3.x on MacOS with libomp 12.0.0. Downgrading to a previous version of libomp solves it.

```
# xgboost macos seg fault when libomp==12.0.0
# passes with libomp==11.1.0

"""
	verify libomp version
		brew list --version libomp
		libomp 12.0.0
	to install libomp 11.1.0
		wget https://raw.githubusercontent.com/chenrui333/homebrew-core/0094d1513ce9e2e85e07443b8b5930ad298aad91/Formula/libomp.rb
        brew unlink libomp
        brew install --build-from-source ./libomp.rb
        brew list --version libomp

"""

import logging
import numpy as np
import xgboost as xgb

def xgboost_unit_tests():
	feature_arr = np.random.uniform(size=(100,5))
	label_arr = np.random.randint(low=0, high=10, size=(100,1))
	data_arr = np.concatenate((feature_arr, label_arr), axis=1)
	#Run Attribute Rank with -O 2
	run_xgboost(data_arr,data_arr)
	logging.info("XGBoost complete")
	return


def run_xgboost(trainarr, valarr):
	trainfeats = trainarr[:,:-1]
	trainlabels = trainarr[:,-1]
	# first seg fault
	dtrain = xgb.DMatrix(trainfeats, label=trainlabels)
	valfeats = valarr[:,:-1]
	vallabels = valarr[:,-1]
	# second seg fault
	dval = xgb.DMatrix(valfeats, label=vallabels)
	return


# Press the green button in the gutter to run the script.
if __name__ == '__main__':
	xgboost_unit_tests()
```

### PR DESCRIPTION
**Pull request by hcho3**
* Use cibuildwheel to build Python wheels targeting MacOS x86_64 and MacOS arm64 (aka Apple Silicon)
* Bundle libomp 11.1.0 into the Python wheels. This step is automatically done by cibuildwheel. Using the version 11.1.0 ensures that we don't get random segfaults when running inside a Conda environment. (See https://github.com/scikit-learn/scikit-learn/pull/21227#issuecomment-933001394 for the list of configurations where segfaults occur.)
* Users no longer need to run `brew instal libomp` prior to installing XGBoost.
* Create a separate YAML file dedicated for wheel building, since there's lots of details involved.

This PR is inspired by https://github.com/scikit-learn/scikit-learn/pull/22109.

Closes #7039

### CODE REVIEW

File: tests/ci_build/build_python_wheels.sh [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+    export CC=/usr/bin/clang
+    export CXX=/usr/bin/clang++
+    export CPPFLAGS="$CPPFLAGS -Xpreprocessor -fopenmp"
+    export CFLAGS="$CFLAGS -I$PREFIX/include"
+    export CXXFLAGS="$CXXFLAGS -I$PREFIX/include"
+    export LDFLAGS="$LDFLAGS -Wl,-rpath,$PREFIX/lib -L$PREFIX/lib -lomp"
+fi
+
+python -m pip install cibuildwheel
+python -m cibuildwheel python-package --output-dir wheelhouse
```
Comment (hcho3) [inline tests/ci_build/build_python_wheels.sh:34]: This command calls `python.py bdist_wheel` to generate the wheel.

File: python-package/setup.py [hunk 2]
```diff
@@ -119,6 +119,9 @@ def build(
                 continue
             cmake_cmd.append('-D' + arg + '=' + value)
 
+        if 'CIBW_TARGET_OSX_ARM64' in os.environ:
```
Comment (trivialfis) [inline python-package/setup.py:122]: Would be great if you can put a brief comment on this environment varilable.

**Review by trivialfis — COMMENTED** [review]
Thank you for working on this!

> Closes #7039

Do we want to back port to 1.5.2?

Could you please document the build process?

**Comment by hcho3** [comment]
Rendered doc: https://xgboost--7621.org.readthedocs.build/en/7621/contrib/ci.html#github-actions

**Review by trivialfis — APPROVED** [review]
Looks cool!
