### PR TITLE
Prevent copying data to host.

### LINKED ISSUE #4751: CPU predictor crashes when training with data stored in GPU memory.
We are working on the GPU training pipeline, to load data into GPU memory and choose `gpu_hist` to run the training locally, non-distributed.

After some basic investigation, found that the first `PredictRaw` in `Learner` will use `cpu_predcitor`, then it crashes at line 71 in file https://github.com/dmlc/xgboost/blob/master/src/predictor/cpu_predictor.cc 

And the crash happens only when parallel is enabled. Error message just before crash is followed

> double free or corruption (out)
double free or corruption (!prev)
double free or corruption (!prev)

What' more interesting is it can pass after even only adding a log print as below,
` 69         }`
 `70         for (int k = 0; k < kUnroll; ++k) {`
 **`71           LOG(WARNING) << "debug == tid = " << tid;`**
 `72           inst[k] = batch[i + k];`
` 73         }`

I think running parallel here may be too fast for GPU -> CPU case, since it may need a little time to copy the batch data from GPU to CPU memory, what's more the sync is lazy per code below from file https://github.com/dmlc/xgboost/blob/master/src/common/host_device_vector.cu . 
`  const std::vector<T>& ConstHostVector() {`
`    LazySyncHost(GPUAccess::kRead);`
`    return data_h_;`
`  }`

Any idea to fix it ? or to fix why cpu_predictor is used when doing the first `PredictRaw` even specifying the tree method as 'gpu_hist'.

### PR DESCRIPTION
**Pull request by trivialfis**
Closes #4751 .

### CODE REVIEW

**Comment by trivialfis** [comment]
There are still small copying scattered over the place.  Including `ColumnSampler` and `label_correct_` in regression obj.  But the big ones are addressed.

File: src/gbm/gbtree.cc [hunk 1]
```diff
@@ -57,6 +57,14 @@ void GBTree::Configure(const Args& cfg) {
 
   monitor_.Init("GBTree");
 
+  if (tparam_.tree_method == TreeMethod::kGPUHist &&
+      std::none_of(cfg.cbegin(), cfg.cend(),
+                   [](std::pair<std::string, std::string> const& arg) {
+                     return arg.first == "predictor";
```
Comment (RAMitchell) [inline src/gbm/gbtree.cc]: Is this check correct? Are you sure this change won't cause the cpu_predictor param to be overwritten?

Comment (trivialfis) [reply src/gbm/gbtree.cc]: @RAMitchell 

- If "predictor" is specified by user, then it should appear in this configuration and be found by this `std::none_of`, hence nothing changes.
- If `predictor` is loaded from binary model, it should also appear in this configuration, nothing changes.
- If `predictor` is never set, and `tree_method` is not `gpu_hist`, nothing changes.
- If `predictor` is never set, but `tree_method` is `gpu_hist`, then `predictor` **is changed** to `gpu_predictor`.

I most certainly don't like the configuration.  In an ideal world there should be only one `hist` method and only one `predictor`, just like our objective functions and metrics.  We dispatch them by `gpu_id` or by #4600 .  But I don't think we can do that in near future ...

Comment (RAMitchell) [reply src/gbm/gbtree.cc]: My mistake, I thought this was checking the second part of the pair for some reason.
