### PR TITLE
[BLOCKING] Handle empty rows in data iterators correctly

### LINKED ISSUE #5848: [jvm-packages] Xgboost4spark 1.1.1 broken and consistently does not work
Some models’ predictions fail on the following error:
Check failed: weights_.Size() == num_row_ (15363 vs. 15362) : Size of weights must equal to number of rows.
The numbers in the error are of course not always the same (but the subtraction is always 1).
The same data/model works on xgboost 0.9.

### PR DESCRIPTION
**Pull request by hcho3**
Fixes #5848.

Diagnosis: https://github.com/dmlc/xgboost/issues/5848#issuecomment-662767268, https://github.com/dmlc/xgboost/issues/5848#issuecomment-662802416. The bug occurs whenever a CSR sparse matrix has empty rows at its end. (Empty rows in the middle of the matrix don't matter.)

Fix. Create a special logic for `IteratorAdapter` and `FileAdapter`, so that the empty rows at the end of the matrix are properly accounted for. I added test cases in Google Test.

### CODE REVIEW

**Comment by hcho3** [comment]
I'd like to backport this bugfix to 1.1.x, since the bug affects potentially many users of JVM packages.

**Comment by trivialfis** [comment]
@hcho3 Can we talk about a new release tomorrow?

**Comment by hcho3** [comment]
@trivialfis Sure. Do you mean patch release (1.1.2) or minor release (1.2.0)?

**Comment by trivialfis** [comment]
Minor release.  It has been a long time.

**Comment by trivialfis** [comment]
I know you got a lot on your plate, I will help with anything I can.

**Comment by CodingCat** [comment]
any idea on how to reproduce the issue in  jvm-packages...I am happy to append a commit

**Comment by CodingCat** [comment]
> Minor release. It has been a long time.

regarding 1.2.x, would consider waiting for https://github.com/dmlc/xgboost/pull/5171?

**Comment by hcho3** [comment]
@CodingCat The reproducible script is at https://github.com/dmlc/xgboost/issues/5848#issuecomment-654749778. I verified that the example fails to run with the current XGBoost, and that it runs successfully with this pull request.

**Comment by hcho3** [comment]
@CodingCat Do you think #5171 is close to be done (ready to merge)?

**Comment by CodingCat** [comment]
> @CodingCat Do you think #5171 is close to be done (ready to merge)?

I think @wbo4958 is trying to add unit test?

**Comment by hcho3** [comment]
I posted in #5734 to discuss 1.2.0 release

**Comment by CodingCat** [comment]
ok...seems I still remember how to write XGBoost code.....test added....

**Comment by CodingCat** [comment]
> Testing rejected. Reason: Today's spending (50.47 USD) exceeded the budget (50.00 USD) allocated for today! The spending limit gets reset every midnight UTC. You can monitor the spending at the dashboard https://xgboost-ci.net/dashboard/.

this is something new?

**Comment by hcho3** [comment]
@CodingCat 

> this is something new?

Yes, I recently added daily throttling to bring cloud cost under control. (Jenkins CI is hosted on AWS.) More details in #5891. In about 30 minutes from now, the budget counter will reset and CI jobs will resume.

File: src/data/simple_dmatrix.cc [hunk 1]
```diff
@@ -153,16 +157,27 @@ SimpleDMatrix::SimpleDMatrix(AdapterT* adapter, float missing, int nthread) {
     info_.num_col_ = adapter->NumColumns();
   }
 
+
   // Synchronise worker columns
   rabit::Allreduce<rabit::op::Max>(&info_.num_col_, 1);
 
   if (adapter->NumRows() == kAdapterUnknownSize) {
-    info_.num_row_ = offset_vec.size() - 1;
+    using IteratorAdapterT
```
Comment (RAMitchell) [inline src/data/simple_dmatrix.cc:165]: Would be good if you could add a comment or two on what the template conditionals are doing.

Comment (hcho3) [reply src/data/simple_dmatrix.cc:165]: Basically we are filtering for `IteratorAdapter` and `FileAdapter` types. I will add a comment.

Comment (hcho3) [reply src/data/simple_dmatrix.cc:165]: Added a comment.

Comment (hcho3) [reply src/data/simple_dmatrix.cc:165]: I created  #5937 to remember to create a less ad-hoc fix in the future.
